# Generated by Django 4.1.7 on 2023-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsprofile',
            name='mentor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
