# Generated by Django 4.1.7 on 2023-03-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('WOMAN', 'woman'), ('MENTOR', 'mentor')], default='WOMAN', max_length=10),
        ),
    ]
