# Generated by Django 4.1.7 on 2023-03-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mentorsprofile_mentor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorsprofile',
            options={'ordering': ['-mentor_id']},
        ),
        migrations.RenameField(
            model_name='mentorsprofile',
            old_name='user',
            new_name='mentor_name',
        ),
    ]
