# Generated by Django 4.1.7 on 2023-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mentorsprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
