# Generated by Django 4.1.7 on 2023-03-19 17:50

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 17, 50, 15, 801600), validators=[home.models.validate_date]),
        ),
    ]
