# Generated by Django 3.2.18 on 2023-03-19 23:29

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 23, 29, 11, 168346), validators=[home.models.validate_date]),
        ),
    ]
